import {Inter, Urbanist} from "next/font/google";
import Footer from "./components/Footer/Footer";
import Nav from "./components/Nav/Nav";
import "./globals.css";

const urbanist = Urbanist({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
